# Generated by Django 5.0 on 2025-09-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0002_voterlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voterlist",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
