# Generated by Django 5.0 on 2025-09-30 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0003_alter_voterlist_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petition",
            name="user",
        ),
        migrations.AddField(
            model_name="petition",
            name="voters",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="VoterList",
        ),
    ]
