# Generated by Django 5.0 on 2025-09-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0004_remove_petition_user_petition_voters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="ownerId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
