# Generated by Django 5.0 on 2025-09-30 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0005_petition_ownerid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="petition",
            name="voters",
            field=models.ManyToManyField(to="petitions.voter"),
        ),
    ]
