# Generated by Django 5.0 on 2025-09-30 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0006_voter_alter_petition_voters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petition",
            name="voters",
        ),
        migrations.RemoveField(
            model_name="petition",
            name="ownerId",
        ),
        migrations.AddField(
            model_name="petition",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VoteBallot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petitions.petition",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Voter",
        ),
    ]
